# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'npm'
      directory: 'example/'
      schedule:
          interval: 'daily'
      ignore:
          - dependency-name: '@babel/core'
          - dependency-name: 'babel-preset-expo'
          - dependency-name: 'expo-splash-screen'
          - dependency-name: 'react'
          - dependency-name: 'react-dom'
          - dependency-name: 'react-native'
          - dependency-name: 'react-native-gesture-handler'
          - dependency-name: 'react-native-reanimated'
          - dependency-name: 'react-native-safe-area-context'
          - dependency-name: 'react-native-screens'
          - dependency-name: 'react-native-unimodules'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
