root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
    - react
    - react-native
    - jest
    - import
extends:
    - '@react-native-community'
    - eslint:all
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
    - prettier
rules:
    '@typescript-eslint/explicit-module-boundary-types': 0
    '@typescript-eslint/no-empty-function': 0
    '@typescript-eslint/no-explicit-any': 0
    '@typescript-eslint/no-var-requires': 0
    capitalized-comments: 0
    class-methods-use-this: 0
    consistent-return: 0
    guard-for-in: 0
    id-length: 0
    init-declarations: 0
    lines-between-class-members: 0
    max-lines-per-function: 0
    max-params: 0
    max-statements: 0
    no-continue: 0
    no-magic-numbers: 0
    no-negated-condition: 0
    no-nested-ternary: 0
    no-param-reassign: 0
    no-shadow: 0
    no-ternary: 0
    no-undefined: 0
    no-underscore-dangle: 0
    no-use-before-define: 0
    no-warning-comments: 0
    one-var: 0
    prefer-destructuring: 0
    sort-imports: 0
    sort-keys: 0
    sort-vars: 0
