name: MAIN

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  yarn_script_validation:
    name: yarn script validation
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        VALIDATION: [lint, test:cov:upload, tr, ts:verify]
        include:
          - VALIDATION: lint
            COMMAND: lint
          - VALIDATION: test:cov:upload
            COMMAND: test:cov:upload
          - VALIDATION: tr
            COMMAND: tr
          - VALIDATION: ts:verify
            COMMAND: ts:verify
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn run ${{ matrix.COMMAND }}
