name: Pull request

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    yarn_script_validation:
        name: yarn script validation
        runs-on: [self-hosted, linux]
        container:
            image: tokenstreet/github-actions-base-image:latest
            credentials:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        strategy:
            matrix:
                VALIDATION: [TypeScript, ESLint, Tests]
                include:
                    - VALIDATION: TypeScript
                      COMMAND: typescript
                    - VALIDATION: ESLint
                      COMMAND: lint
                    - VALIDATION: Tests
                      COMMAND: test
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3.1.1
              with:
                  node-version: 16
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn install --cwd example --frozen-lockfile
            - run: yarn ${{ matrix.COMMAND }}
